-- daily_trips_weather: daily Citibike ridership joined to NYC daily weather.
--
-- This is the single source the Streamlit dashboard reads. It LEFT JOINs the
-- materialized daily ridership (m_daily_trips) onto the materialized NYC daily
-- weather (nyu-datasets.weather.m_weather_daily_nyc) on the calendar date, so the
-- full 2013 -> present trips history is preserved even for the most recent days
-- that the weather feed has not published yet (weather currently lags trips by a
-- couple of weeks; those rows keep NULL weather).
--
-- Joining the two *materialized* tables keeps the dashboard query tiny (a few
-- thousand rows on each side) and cheap, instead of re-scanning 300M+ trips.
-- Generated by src/citibike_pipeline/analytics.py; this file mirrors it.

CREATE OR REPLACE VIEW `nyu-datasets.citibike.daily_trips_weather` AS
SELECT
  t.*,
  -- calendar context from the weather feed
  d.year, d.month, d.day_of_week, d.is_weekend, d.season,
  -- temperature (Fahrenheit)
  d.tmin_f, d.tmax_f, d.tavg_f,
  -- precipitation
  d.prcp_inches, d.snow_inches,
  -- convenience weather flags (1/0)
  d.is_rainy, d.is_snowy, d.is_hot_day, d.is_freezing
FROM `nyu-datasets.citibike.m_daily_trips` AS t
LEFT JOIN `nyu-datasets.weather.m_weather_daily_nyc` AS d
  ON t.date = d.date
;
