-- daily_trips: one row per calendar day, aggregating every Citibike trip in the
-- canonical table (2013 -> present, NYC + Jersey City).
--
-- This is the trips side of the weather-effects dashboard. It is joined 1:1
-- against nyu-datasets.weather.m_weather_daily_nyc in daily_trips_weather.
--
-- Day key. Citibike stores start_time as naive *local* (America/New_York)
-- wall-clock time — the trip-hour histogram peaks at 08:00 and 17:00 with no UTC
-- shift — so DATE(start_time) is already the local calendar day and lines up with
-- the NYC weather dates without any timezone conversion.
--
-- Era de-duplication. trips_unified double-counts January 2021: the 2021 annual
-- archive ships that month in the legacy layout, and Citibike *also* re-published
-- January 2021 in the current layout, so both copies were loaded (~1.1M trips
-- twice). It also carries ~1.5k stray current-era rows in 2019-2020 with corrupt
-- timestamps. The current layout's canonical data begins 2021-02-01; legacy
-- (which cleanly ends 2021-01-31) owns every earlier day. Keeping current rows
-- only from 2021-02-01 puts each calendar day in exactly one era per region.
--
-- Source: the trips_unified view (the canonical union of every era/region), so
-- `make daily` is self-contained and always reflects the latest loaded Parquet —
-- it never depends on m_trips_unified having been re-materialized first.
-- Generated by src/citibike_pipeline/analytics.py; this file mirrors it for humans.

CREATE OR REPLACE VIEW `nyu-datasets.citibike.daily_trips` AS
SELECT
  DATE(start_time)                                          AS date,
  COUNT(*)                                                  AS num_trips,
  COUNTIF(member_casual = 'member')                         AS num_member_trips,
  COUNTIF(member_casual = 'casual')                         AS num_casual_trips,
  COUNTIF(region = 'NYC' AND member_casual = 'member')      AS num_member_trips_nyc,
  COUNTIF(region = 'NYC' AND member_casual = 'casual')      AS num_casual_trips_nyc,
  COUNTIF(region = 'JC'  AND member_casual = 'member')      AS num_member_trips_jc,
  COUNTIF(region = 'JC'  AND member_casual = 'casual')      AS num_casual_trips_jc,
  COUNTIF(region = 'NYC')                                   AS num_nyc_trips,
  COUNTIF(region = 'JC')                                    AS num_jc_trips,
  COUNTIF(rideable_type = 'classic_bike')                   AS num_classic_trips,
  COUNTIF(rideable_type = 'electric_bike')                  AS num_electric_trips,
  ROUND(AVG(trip_duration_seconds) / 60, 3)                 AS avg_trip_duration_minutes,
  ROUND(APPROX_QUANTILES(trip_duration_seconds, 100)[OFFSET(50)] / 60, 3)
                                                            AS median_trip_duration_minutes,
  ROUND(AVG(distance_meters), 1)                            AS avg_distance_meters
FROM `nyu-datasets.citibike.trips_unified`
WHERE NOT (source_era = 'current' AND DATE(start_time) < DATE '2021-02-01')
GROUP BY date
;
