-- daily_trips_weather: daily Citibike ridership joined to NYC daily weather.
--
-- This is the single source the Streamlit dashboard reads. It LEFT JOINs the
-- materialized daily ridership (m_daily_trips) onto the materialized NYC daily
-- weather (nyu-datasets.weather.m_weather_daily_nyc) on the calendar date, so the
-- full 2013 -> present trips history is preserved even for the most recent days
-- that the weather feed has not published yet (weather currently lags trips by a
-- couple of weeks; those rows keep NULL weather).
--
-- `d.* EXCEPT(date)` carries every weather column through, so when the weather
-- table gains measurements they appear in the dashboard's source automatically
-- (no edit here). As of this writing that is:
--   * calendar context : year, month, day, day_of_week, is_weekend, season
--   * temperature       : tmin_f, tmax_f, tavg_f
--   * precipitation/snow: prcp_inches, snow_inches, snow_depth_inches
--   * wind              : wind_avg_mph, wind_gust_mph, wind_dir_deg
--   * humidity/comfort  : rh_avg, rh_min, rh_max, dewpoint_f, wetbulb_f  (2016-2024)
--   * pressure          : sea_level_pressure_hpa                         (2016-2024)
--   * condition flags   : is_rainy, is_snowy, is_hot_day, is_freezing,
--                         is_humid, is_foggy, is_thunder, is_hazy
-- (`date` is dropped from the right side so it is not duplicated; t.date is the key.)
--
-- Joining the two *materialized* tables keeps the dashboard query tiny (a few
-- thousand rows on each side) and cheap, instead of re-scanning 300M+ trips.
-- Generated by src/citibike_pipeline/analytics.py; this file mirrors it.

CREATE OR REPLACE VIEW `nyu-datasets.citibike.daily_trips_weather` AS
SELECT
  t.*,
  d.* EXCEPT(date)
FROM `nyu-datasets.citibike.m_daily_trips` AS t
LEFT JOIN `nyu-datasets.weather.m_weather_daily_nyc` AS d
  ON t.date = d.date
;
