-- hourly_trips: one row per local clock hour of Citibike ridership.
--
-- The hourly companion of daily_trips (same source, same splits, same era
-- de-duplication — see sql/daily_trips.sql for the rationale of the cutover
-- predicate). Two points specific to the hourly grain:
--
-- * HOUR KEY. Citibike stores start_time as naive *local* (America/New_York)
--   wall-clock time, so TIMESTAMP_TRUNC(start_time, HOUR) is already the local
--   clock hour — no timezone conversion. It lines up 1:1 with the hourly
--   weather mart's obs_time_local (which is derived from the LCD LST stamps
--   precisely so the two sides meet on the same wall clock).
--
-- * ZERO HOURS. Hours with no trips produce no row (GROUP BY can't emit what
--   it never saw). Rare system-wide (overnight winter storms), common for
--   Jersey City's small early-years system. Consumers averaging "trips by
--   hour" should zero-fill the (date x 24h) grid first, as the dashboard does.
--
-- Generated by src/citibike_pipeline/analytics.py; this file mirrors it.

CREATE OR REPLACE VIEW `nyu-datasets.citibike.hourly_trips` AS
SELECT
  TIMESTAMP_TRUNC(start_time, HOUR)                         AS hour_ts,
  DATE(start_time)                                          AS date,
  EXTRACT(HOUR FROM start_time)                             AS hour,
  COUNT(*)                                                  AS num_trips,
  COUNTIF(member_casual = 'member')                         AS num_member_trips,
  COUNTIF(member_casual = 'casual')                         AS num_casual_trips,
  COUNTIF(region = 'NYC' AND member_casual = 'member')      AS num_member_trips_nyc,
  COUNTIF(region = 'NYC' AND member_casual = 'casual')      AS num_casual_trips_nyc,
  COUNTIF(region = 'JC'  AND member_casual = 'member')      AS num_member_trips_jc,
  COUNTIF(region = 'JC'  AND member_casual = 'casual')      AS num_casual_trips_jc,
  COUNTIF(region = 'NYC')                                   AS num_nyc_trips,
  COUNTIF(region = 'JC')                                    AS num_jc_trips,
  COUNTIF(rideable_type = 'classic_bike')                   AS num_classic_trips,
  COUNTIF(rideable_type = 'electric_bike')                  AS num_electric_trips,
  ROUND(AVG(trip_duration_seconds) / 60, 3)                 AS avg_trip_duration_minutes,
  ROUND(AVG(distance_meters), 1)                            AS avg_distance_meters
FROM `nyu-datasets.citibike.trips_unified`
WHERE NOT (source_era = 'current' AND DATE(start_time) < DATE '2021-02-01')
GROUP BY hour_ts, date, hour
;
