-- hourly_trips_weather: hourly Citibike ridership joined to hourly NYC weather.
--
-- The hourly companion of daily_trips_weather: m_hourly_trips LEFT JOINed to
-- the Stage-W hourly weather mart (nyu-datasets.weather.m_weather_hourly_nyc,
-- NOAA LCD v2 for Central Park — the same station behind the daily weather).
--
-- The weather side first collapses the observation-level mart to one row per
-- local clock hour:
--   * the routine FM-15 METAR (taken at :51 past each hour) is the hour's
--     canonical reading; FM-16 specials only fill the rare hours without one;
--   * FM-15 HourlyPrecipitation is already the past-hour accumulation, so
--     specials are never averaged in (that would double-count partial sums) —
--     an FM-16-only hour takes MAX as the best available floor;
--   * gusts take the hour's max; the falling-now flags (is_raining, is_snowing,
--     is_foggy, is_thunder, is_hazy) are 1 if ANY observation in the hour saw
--     the phenomenon.
--
-- Both hour keys are naive local wall-clock (trips natively; weather via
-- obs_time_local, derived from the LCD local-standard-time stamps), so the
-- join is local-to-local with no DST seam. Hours where the station reported
-- nothing keep NULL weather, mirroring the daily join's behavior.
--
-- Generated by src/citibike_pipeline/analytics.py; this file mirrors it.

CREATE OR REPLACE VIEW `nyu-datasets.citibike.hourly_trips_weather` AS
WITH w AS (
  SELECT
    DATETIME_TRUNC(obs_time_local, HOUR) AS hour_dt,
    COALESCE(AVG(IF(report_type = 'FM-15', temp_f, NULL)), AVG(temp_f))           AS temp_f,
    COALESCE(AVG(IF(report_type = 'FM-15', dewpoint_f, NULL)), AVG(dewpoint_f))   AS dewpoint_f,
    COALESCE(AVG(IF(report_type = 'FM-15', wetbulb_f, NULL)), AVG(wetbulb_f))     AS wetbulb_f,
    COALESCE(AVG(IF(report_type = 'FM-15', rh_pct, NULL)), AVG(rh_pct))           AS rh_pct,
    COALESCE(AVG(IF(report_type = 'FM-15', prcp_inches, NULL)), MAX(prcp_inches)) AS prcp_inches,
    COALESCE(AVG(IF(report_type = 'FM-15', wind_mph, NULL)), AVG(wind_mph))       AS wind_mph,
    MAX(wind_gust_mph)                                                            AS wind_gust_mph,
    COALESCE(AVG(IF(report_type = 'FM-15', visibility_miles, NULL)),
             AVG(visibility_miles))                                               AS visibility_miles,
    MAX(is_raining) AS is_raining,
    MAX(is_snowing) AS is_snowing,
    MAX(is_foggy)   AS is_foggy,
    MAX(is_thunder) AS is_thunder,
    MAX(is_hazy)    AS is_hazy
  FROM `nyu-datasets.weather.m_weather_hourly_nyc`
  GROUP BY hour_dt
)
SELECT
  t.*,
  w.* EXCEPT(hour_dt)
FROM `nyu-datasets.citibike.m_hourly_trips` AS t
LEFT JOIN w
  ON DATETIME(t.hour_ts) = w.hour_dt
;
