-- station_counts_monthly: one row per (month, region) with the number of distinct
-- physical stations that originated trips and the trip count. It lets the dashboard
-- and notebook express ridership *per station* — separating real usage growth from
-- network coverage (the system roughly 7x'd its station count over 2014 -> 2025).
--
-- Reconciliation (the hard part). A *continuous* count of physical stations across
-- the 2021 schema change needs a stable key, and the obvious ones fail:
--   * station ids churn across eras — legacy integers (497) vs current strings
--     (5905.14) — so COUNT(DISTINCT start_station_id) jumps 2,779 -> 1,750 -> 2,350
--     across 2021-2023 with no real network change;
--   * current-era coordinates are per-trip *bike GPS*, not a fixed station anchor, so
--     ROUND(lat, lng) explodes to >12k phantom "stations" per year.
-- The station *name* (the intersection) is stable across eras, so we reconcile on a
-- normalized name (upper-cased, whitespace-collapsed). `num_stations` counts distinct
-- names that originated >=1 trip in the month ("active"); at the monthly grain that is
-- effectively the roster.
--
-- Era de-duplication mirrors daily_trips: drop current-layout rows before 2021-02-01
-- (January 2021 is double-published, plus stray corrupt-timestamp current rows in
-- 2019-2020), so trip counts line up with the other marts.
--
-- Generated by src/citibike_pipeline/analytics.py; this file mirrors it for humans.

CREATE OR REPLACE VIEW `nyu-datasets.citibike.station_counts_monthly` AS
SELECT
  DATE_TRUNC(DATE(start_time), MONTH)                       AS month,
  region,
  COUNT(DISTINCT UPPER(TRIM(REGEXP_REPLACE(start_station_name, r'\s+', ' '))))
                                                            AS num_stations,
  COUNT(*)                                                  AS num_trips
FROM `nyu-datasets.citibike.trips_unified`
WHERE NOT (source_era = 'current' AND DATE(start_time) < DATE '2021-02-01')
  AND start_station_name IS NOT NULL
GROUP BY month, region
;
