-- trips_unified: one canonical, lossless union of every Citibike trip era.
--
-- This IMPROVES on the existing `all_trips` view (which it leaves untouched):
--   * keeps every column from both eras as a true superset (ride_id, bike_id,
--     birth_year, gender are NULL where the source era didn't provide them);
--   * exposes trip_duration in SECONDS (legacy's explicit value, computed for
--     the current era) instead of silently switching to minutes;
--   * adds provenance: region, source_era, and source_file (the GCS object the
--     row was read from, via the _FILE_NAME pseudo-column);
--   * keeps the Subscriber->member / Customer->casual mapping and distance_meters.
--
-- It is generated by src/citibike_pipeline/load_bigquery.py from the per-era
-- external tables. The two NYC branches below are what is deployed today. Once
-- Jersey City Parquet has been loaded (`make load-jc`), load_bigquery.py appends
-- the matching JC branches (region = 'JC') to this same shape.

CREATE OR REPLACE VIEW `nyu-datasets.citibike.trips_unified` AS

-- ── Legacy layout (≈2013–2021): trips_2013_2021 ────────────────────────────────
SELECT
  CAST(NULL AS STRING)                       AS ride_id,
  CAST(NULL AS STRING)                       AS rideable_type,
  start_time,
  stop_time,
  -- legacy ships an explicit duration in seconds; fall back to a computed value
  CAST(COALESCE(trip_duration,
                TIMESTAMP_DIFF(stop_time, start_time, SECOND)) AS INT64)
                                             AS trip_duration_seconds,
  CAST(start_station_id AS STRING)           AS start_station_id,
  start_station_name,
  start_station_latitude,
  start_station_longitude,
  CAST(end_station_id AS STRING)             AS end_station_id,
  end_station_name,
  end_station_latitude,
  end_station_longitude,
  CASE user_type WHEN 'Subscriber' THEN 'member'
                 WHEN 'Customer'   THEN 'casual' END
                                             AS member_casual,
  CAST(bike_id AS STRING)                    AS bike_id,
  SAFE_CAST(birth_year AS INT64)             AS birth_year,
  SAFE_CAST(gender AS INT64)                 AS gender,
  ST_DISTANCE(ST_GEOGPOINT(start_station_longitude, start_station_latitude),
              ST_GEOGPOINT(end_station_longitude,   end_station_latitude))
                                             AS distance_meters,
  'NYC'                                      AS region,
  'legacy'                                   AS source_era,
  _FILE_NAME                                 AS source_file
FROM `nyu-datasets.citibike.trips_2013_2021`

UNION ALL

-- ── Current layout (2021 → present): trips_2021_now ────────────────────────────
SELECT
  ride_id,
  rideable_type,
  start_time,
  stop_time,
  CAST(TIMESTAMP_DIFF(stop_time, start_time, SECOND) AS INT64)
                                             AS trip_duration_seconds,
  CAST(start_station_id AS STRING)           AS start_station_id,
  start_station_name,
  start_station_latitude,
  start_station_longitude,
  CAST(end_station_id AS STRING)             AS end_station_id,
  end_station_name,
  end_station_latitude,
  end_station_longitude,
  member_casual,
  CAST(NULL AS STRING)                       AS bike_id,
  CAST(NULL AS INT64)                        AS birth_year,
  CAST(NULL AS INT64)                        AS gender,
  ST_DISTANCE(ST_GEOGPOINT(start_station_longitude, start_station_latitude),
              ST_GEOGPOINT(end_station_longitude,   end_station_latitude))
                                             AS distance_meters,
  'NYC'                                      AS region,
  'current'                                  AS source_era,
  _FILE_NAME                                 AS source_file
FROM `nyu-datasets.citibike.trips_2021_now`
;
