-- weather_hourly_nyc: hourly Central Park observations (NOAA LCD v2).
--
-- The daily mart (weather_daily_nyc, from GHCN-Daily) summarizes the very same
-- station this view exposes at observation level: LCD v2 publishes the hourly
-- ASOS record for NY CITY CENTRAL PARK (GHCN id USW00094728, WBAN 94728, ICAO
-- KNYC). Rows are FM-15 routine hourly METARs (~24/day, at :51 past the hour)
-- plus FM-16 special observations; the SOD/SOM daily/monthly summary rows of
-- the source files are dropped at extract — dailies are the daily mart's domain.
--
-- Three source facts this view pins:
--
-- * TIME BASIS. LCD v2 stamps observations in local STANDARD time year-round
--   (UTC-5, never DST) — verified by matching identical observations against
--   the UTC-stamped ISD record in both January and July (+5h both seasons).
--   Citibike trips carry naive local wall-clock (America/New_York, DST-aware),
--   so the joinable key is obs_time_local = LST -> UTC (+5h) -> America/New_York
--   ('Etc/GMT+5' is fixed UTC-5 in the POSIX sign convention, i.e. exactly LST).
--   Do NOT join trips on obs_time_lst: it is off by one hour all summer.
--
-- * UNITS. LCD v2 is SI (degC, mm, m/s, km, hPa). The Parquet under
--   weather/lcd/parquet/ keeps the SI values faithfully; this view adds the
--   imperial conversions used by the daily mart (degF, inches, mph, miles).
--
-- * VALUE MARKERS (handled at extract, documented here): 'T' trace
--   precipitation -> 0.0 (as GHCN daily treats trace); trailing 's' = NCEI
--   "suspect" QC flag -> NULL (the hourly analog of the daily mart's
--   qflag IS NULL filter); trailing 'V' = "variable", value stands; 'VRB'
--   wind direction -> NULL.
--
-- Snow has NO hourly accumulation source anywhere: snowfall/depth are
-- once-daily manual measurements (use the daily mart). Hourly snow appears
-- only as the is_snowing present-weather flag.
--
-- Flags: is_foggy / is_thunder / is_hazy mirror the daily mart's WT01/WT03/WT08
-- semantics (FG not BR — mist is excluded there too). is_raining / is_snowing
-- are *falling-now* flags; the daily is_rainy / is_snowy mean "accumulated
-- today", which is a different statement.
--
-- Coverage bonus vs the daily mart: dew point / RH / wet-bulb are populated
-- from 2013 here, while the daily GHCN ADPT/RHAV elements only begin ~2016.
--
-- Generated by src/citibike_pipeline/weather_hourly.py; this file mirrors it.

CREATE OR REPLACE VIEW `nyu-datasets.weather.weather_hourly_nyc` AS
WITH obs AS (
  SELECT
    -- The Parquet column physically holds LST wall times, but BigQuery
    -- surfaces external Parquet timestamps as UTC-labeled TIMESTAMPs:
    -- DATETIME() recovers the naive LST wall time, TIMESTAMP(.., 'Etc/GMT+5')
    -- re-anchors it to the fixed UTC-5 zone it really lives in.
    * EXCEPT(obs_time_lst),
    DATETIME(obs_time_lst) AS obs_time_lst,
    TIMESTAMP(DATETIME(obs_time_lst), 'Etc/GMT+5') AS obs_time_utc
  FROM `nyu-datasets.weather.lcd_hourly_nyc`
)
SELECT
  station_id,
  report_type,
  obs_time_lst,
  obs_time_utc,
  DATETIME(obs_time_utc, 'America/New_York')                    AS obs_time_local,
  DATE(obs_time_utc, 'America/New_York')                        AS date_local,
  EXTRACT(HOUR FROM DATETIME(obs_time_utc, 'America/New_York')) AS hour_local,
  ROUND(temp_c * 9/5 + 32, 1)         AS temp_f,
  ROUND(dewpoint_c * 9/5 + 32, 1)     AS dewpoint_f,
  ROUND(wetbulb_c * 9/5 + 32, 1)      AS wetbulb_f,
  rh_pct,
  ROUND(precip_mm / 25.4, 3)          AS prcp_inches,
  slp_hpa                             AS sea_level_pressure_hpa,
  ROUND(wind_speed_ms * 2.23694, 1)   AS wind_mph,
  ROUND(wind_gust_ms * 2.23694, 1)    AS wind_gust_mph,
  wind_dir_deg,
  ROUND(visibility_km / 1.609344, 1)  AS visibility_miles,
  IF(REGEXP_CONTAINS(IFNULL(present_weather, ''), r'RA|DZ'), 1, 0)       AS is_raining,
  IF(REGEXP_CONTAINS(IFNULL(present_weather, ''), r'SN|SG|PL|GS'), 1, 0) AS is_snowing,
  IF(REGEXP_CONTAINS(IFNULL(present_weather, ''), r'FG'), 1, 0)          AS is_foggy,
  IF(REGEXP_CONTAINS(IFNULL(present_weather, ''), r'TS'), 1, 0)          AS is_thunder,
  IF(REGEXP_CONTAINS(IFNULL(present_weather, ''), r'HZ'), 1, 0)          AS is_hazy,
  sky_conditions,
  present_weather,
  temp_c, dewpoint_c, wetbulb_c, precip_mm,
  wind_speed_ms, wind_gust_ms, visibility_km,
  source_file
FROM obs
;
